#! /system/xbin/bash
#
# Copyright 2011-2013, The SaberMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Scirpt by Paul Beeler (SparksCo)

# Check if logd directory exsist
if [ -d /data/logd ];
then
    echo ""
else
    mkdir /data/logd
fi

getbuildprop () {
    if [ -f /system/build.prop ];
    then
        result=(`grep $1 system/build.prop | tr -d '\r' | tr '=' ' '`)
        echo "${result[1]}"
        echo ""
    else
        echo "/system/build.prop not found, now exiting"
        echo ""
        sleep 10
        exit 1
    fi
}

DENSITY=$(getbuildprop ro.sf.lcd_density)
if [[ $DENSITY == "213"* ]];
then
    # call with a prompt string or use a default
    read -r -p "${1:-Stock UI detected.  Change to SaberMod UI? [Y/n]} " response
    case $response in
        [yY][eE][sS]|[yY])
        # Make sure the system has read/write access
        bash /etc/mount-rw
        # Set LCD density to 183
        sed -i 's/ro.sf.lcd_density=213//g' /system/build.prop
        echo "ro.sf.lcd_density=183" >> /system/build.prop
        echo ""
        echo "183" > /data/logd/lcd-density.log
        echo "All finished, your Nexus will now reboot to apply changes in 10 seconds unless you close this window"
        # set system back to read only access
        bash /etc/mount-ro
        sleep 10
        reboot
        ;;
    *)
        echo ""
        echo "No changes applied, now exiting"
        exit 1
        ;;
    esac
else
    if [[ $DENSITY == "183"* ]];
    then
        # call with a prompt string or use a default
        read -r -p "${1:-SaberMod UI detected.  Change back to Stock UI? [Y/n]} " response
        case $response in
            [yY][eE][sS]|[yY])
            # Make sure the system has read/write access
            bash /etc/mount-rw
            # Set LCD density to 213
            sed -i 's/ro.sf.lcd_density=183//g' /system/build.prop
            echo "ro.sf.lcd_density=213" >> /system/build.prop
            echo ""
            echo "213" > /data/logd/lcd-density.log
            echo "All finished, your Nexus will now reboot to apply changes in 10 seconds unless you close this window"
            # set system back to read only access
            bash /etc/mount-ro
            sleep 10
            reboot
            ;;
        *)
            echo ""
            echo "No changes applied, now exiting"
            exit 1
            ;;
        esac
    else
        echo ""
        # call with a prompt string or use a default
        read -r -p "${1:-Could not detect your LCD density values.  Restore back to stock?  Y for stock UI, n for SaberMod UI.  Or you can close this window now to exit. [Y/n]} " response
        case $response in
            [yY][eE][sS]|[yY])
            # Make sure the system has read/write access
            bash /etc/mount-rw
            # Set LCD density to 213
            sed -i 's/ro.sf.lcd_density=*//g' /system/build.prop
            echo "ro.sf.lcd_density=213" >> /system/build.prop
            echo ""
            echo "213" > /data/logd/lcd-density.log
            echo "All finished, your Nexus will now reboot to apply changes in 10 seconds unless you close this window"
            # set system back to read only access
            bash /etc/mount-ro
            sleep 10
            reboot
            ;;
        *)
            # Make sure the system has read/write access
            bash /etc/mount-rw
            # Set LCD density to 183
            sed -i 's/ro.sf.lcd_density=*//g' /system/build.prop
            echo "ro.sf.lcd_density=183" >> /system/build.prop
            echo ""
            echo "183" > /data/logd/lcd-density.log
            echo "All finished, your Nexus will now reboot to apply changes in 10 seconds unless you close this window"
            # set system back to read only access
            bash /etc/mount-ro
            sleep 10
            reboot
            ;;
        esac
    fi
fi
