#!/system/bin/sh
#
# Copyright (C) 2012-2013 The SaberMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# Activate zram
busybox modprobe zram num_devices=8;
busybox echo 1 > /sys/block/zram0/reset;
busybox echo 1 > /sys/block/zram1/reset;
busybox echo 1 > /sys/block/zram2/reset;
busybox echo 1 > /sys/block/zram3/reset;
busybox echo 1 > /sys/block/zram4/reset;
busybox echo 1 > /sys/block/zram5/reset;
busybox echo 1 > /sys/block/zram6/reset;
busybox echo 1 > /sys/block/zram7/reset;
busybox echo $((12*1024*1024)) > /sys/block/zram0/disksize;
busybox echo $((12*1024*1024)) > /sys/block/zram1/disksize;
busybox echo $((12*1024*1024)) > /sys/block/zram2/disksize;
busybox echo $((12*1024*1024)) > /sys/block/zram3/disksize;
busybox echo $((12*1024*1024)) > /sys/block/zram4/disksize;
busybox echo $((12*1024*1024)) > /sys/block/zram5/disksize;
busybox echo $((12*1024*1024)) > /sys/block/zram6/disksize;
busybox echo $((12*1024*1024)) > /sys/block/zram7/disksize;
busybox mkswap /dev/block/zram0;
busybox mkswap /dev/block/zram1;
busybox mkswap /dev/block/zram2;
busybox mkswap /dev/block/zram3;
busybox mkswap /dev/block/zram4;
busybox mkswap /dev/block/zram5;
busybox mkswap /dev/block/zram6;
busybox mkswap /dev/block/zram7;
busybox swapon /dev/block/zram0;
busybox swapon /dev/block/zram1;
busybox swapon /dev/block/zram2;
busybox swapon /dev/block/zram3;
busybox swapon /dev/block/zram4;
busybox swapon /dev/block/zram5;
busybox swapon /dev/block/zram6;
busybox swapon /dev/block/zram7;
