#!/system/bin/sh
#
# Copyright 2011-2013, The SaberMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Scirpt by Paul Beeler (SparksCo)
# Check if this is a fresh ROM flash to run a one time check of LCD density

if [ -e /system/etc/init.d/06tmp-lcd ];
then
    # Run the check of LCD density
    bash /system/etc/init.d/06tmp-lcd
    # Set system with read/write access
    bash /etc/mount-rw
    # Remove the script since we don't need to check anymore
    rm /system/etc/init.d/06tmp-lcd
    # Set system back to read only access
    bash /etc/mount-rw
fi;
