#! /system/xbin/bash
#
# Copyright 2011-2013, The SaberMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Scirpt by Paul Beeler (SparksCo)
# Check if LCD density was changed or not and restore values
LOG=/data/logd/lcd-density.log
if [ -e $LOG ];
then
    if [[ "$(cat $LOG" == "183" ]];
    then
        # Set system to read/write access
        bash /etc/mount-rw
        # Restore SaberMod UI
        sed -i 's/ro.sf.lcd_density=213//g' /system/build.prop
        echo "ro.sf.lcd_density=183" >> /system/build.prop
        bash /etc/mount-ro
    fi;
fi;
